.TH "obj/Debug/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/Debug/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
