.TH "App.axaml.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App.axaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.App\fP"
.br
.RI "Основной класс приложения Avalonia\&. Отвечает за инициализацию приложения, создание главного окна и управление жизненным циклом\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
