.TH "BattleShipGame.Logic.BotTurnResult" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Logic.BotTurnResult \- Результат хода бота\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBotTurnResult\fP (bool continueTurn, bool isPlayerTurn, bool gameOver)"
.br
.RI "Возвращает результат атаки бота выбранной сложности\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBContinueTurn\fP\fR [get]\fP"
.br
.RI "Флаг возможности продолжения хода\&. "
.ti -1c
.RI "bool \fBIsPlayerTurn\fP\fR [get]\fP"
.br
.RI "Флаг проверки хода игрока\&. "
.ti -1c
.RI "bool \fBGameOver\fP\fR [get]\fP"
.br
.RI "Флаг окончания игры\&. "
.in -1c
.SH "Detailed Description"
.PP 
Результат хода бота\&. 
.PP
Definition at line \fB300\fP of file \fBBotLogic\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Logic\&.BotTurnResult\&.BotTurnResult (bool continueTurn, bool isPlayerTurn, bool gameOver)"

.PP
Возвращает результат атаки бота выбранной сложности\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontinueTurn\fP Возможность продолжения хода\&.
.br
\fIisPlayerTurn\fP Проверка хода игрока\&.
.br
\fIgameOver\fP Флаг окончания игры\&.
.RE
.PP

.PP
Definition at line \fB317\fP of file \fBBotLogic\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool BattleShipGame\&.Logic\&.BotTurnResult\&.ContinueTurn\fR [get]\fP"

.PP
Флаг возможности продолжения хода\&. 
.PP
Definition at line \fB304\fP of file \fBBotLogic\&.cs\fP\&.
.SS "bool BattleShipGame\&.Logic\&.BotTurnResult\&.GameOver\fR [get]\fP"

.PP
Флаг окончания игры\&. 
.PP
Definition at line \fB308\fP of file \fBBotLogic\&.cs\fP\&.
.SS "bool BattleShipGame\&.Logic\&.BotTurnResult\&.IsPlayerTurn\fR [get]\fP"

.PP
Флаг проверки хода игрока\&. 
.PP
Definition at line \fB306\fP of file \fBBotLogic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
