.TH "BattleShipGame.ServerLogic.NetworkMessage" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.ServerLogic.NetworkMessage
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBType\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, string > \fBData\fP = new()\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBNetworking\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, string> BattleShipGame\&.ServerLogic\&.NetworkMessage\&.Data = new()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBNetworking\&.cs\fP\&.
.SS "string BattleShipGame\&.ServerLogic\&.NetworkMessage\&.Type\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBNetworking\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
