.TH "BattleShipGame.Views.OpponentDisconnectWindow" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Views.OpponentDisconnectWindow \- Диалоговое окно уведомления о потере соединения с соперником\&. Используется для информирования игрока о разрыве сетевого соединения\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpponentDisconnectWindow\fP ()"
.br
.RI "Инициализирует новый экземпляр класса \fBOpponentDisconnectWindow\fP\&. Настраивает отображение сообщения и обработчик кнопки подтверждения\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessage\fP = string\&.Empty\fR [get, set]\fP"
.br
.RI "Получает или устанавливает сообщение для отображения\&. "
.in -1c
.SH "Detailed Description"
.PP 
Диалоговое окно уведомления о потере соединения с соперником\&. Используется для информирования игрока о разрыве сетевого соединения\&. 
.PP
Definition at line \fB9\fP of file \fBOpponentDisconnectWindow\&.axaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Views\&.OpponentDisconnectWindow\&.OpponentDisconnectWindow ()"

.PP
Инициализирует новый экземпляр класса \fBOpponentDisconnectWindow\fP\&. Настраивает отображение сообщения и обработчик кнопки подтверждения\&. 
.PP
Definition at line \fB20\fP of file \fBOpponentDisconnectWindow\&.axaml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string BattleShipGame\&.Views\&.OpponentDisconnectWindow\&.Message = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Получает или устанавливает сообщение для отображения\&. 
.PP
Definition at line \fB14\fP of file \fBOpponentDisconnectWindow\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
