.TH "BattleShipGame.Views.ConfirmDialogWindow" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Views.ConfirmDialogWindow \- Диалоговое окно подтверждения действия с выбором Да/Нет\&. Используется для подтверждения критических действий (выход из игры, новая игра и т\&.д\&.)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfirmDialogWindow\fP ()"
.br
.RI "Инициализирует новый экземпляр класса \fBConfirmDialogWindow\fP\&. Настраивает обработчики событий для кнопок подтверждения и отмены\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessage\fP\fR [get, set]\fP"
.br
.RI "Текст сообщения\&. "
.in -1c
.SH "Detailed Description"
.PP 
Диалоговое окно подтверждения действия с выбором Да/Нет\&. Используется для подтверждения критических действий (выход из игры, новая игра и т\&.д\&.)\&. 

Возвращает boolean результат: true для подтверждения, false для отмены\&. 
.PP
Definition at line \fB12\fP of file \fBConfirmDialogWindow\&.axaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Views\&.ConfirmDialogWindow\&.ConfirmDialogWindow ()"

.PP
Инициализирует новый экземпляр класса \fBConfirmDialogWindow\fP\&. Настраивает обработчики событий для кнопок подтверждения и отмены\&. 
.PP
Definition at line \fB32\fP of file \fBConfirmDialogWindow\&.axaml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string BattleShipGame\&.Views\&.ConfirmDialogWindow\&.Message\fR [get]\fP, \fR [set]\fP"

.PP
Текст сообщения\&. Сообщение, отображаемое в диалоговом окне\&. 
.PP
Definition at line \fB19\fP of file \fBConfirmDialogWindow\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
