.TH "BattleShipGame.Views.GameOverWindow" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Views.GameOverWindow \- Диалоговое окно, отображаемое при завершении игры в локальном режиме\&. Показывает результат игры и предоставляет опции для дальнейших действий\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameOverWindow\fP ()"
.br
.RI "Инициализирует новый экземпляр класса \fBGameOverWindow\fP\&. Настраивает текст результата и обработчики событий кнопок\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBGameOverResult\fP? \fBResult\fP\fR [get]\fP"
.br
.RI "Получает выбранный пользователем результат\&. "
.ti -1c
.RI "bool \fBIsWin\fP\fR [get, set]\fP"
.br
.RI "Получает или устанавливает флаг победы текущего игрока\&. "
.ti -1c
.RI "string \fBWinnerName\fP = string\&.Empty\fR [get, set]\fP"
.br
.RI "Получает или устанавливает имя победителя\&. "
.in -1c
.SH "Detailed Description"
.PP 
Диалоговое окно, отображаемое при завершении игры в локальном режиме\&. Показывает результат игры и предоставляет опции для дальнейших действий\&. 
.PP
Definition at line \fB20\fP of file \fBGameOverWindow\&.axaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Views\&.GameOverWindow\&.GameOverWindow ()"

.PP
Инициализирует новый экземпляр класса \fBGameOverWindow\fP\&. Настраивает текст результата и обработчики событий кнопок\&. 
.PP
Definition at line \fB41\fP of file \fBGameOverWindow\&.axaml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool BattleShipGame\&.Views\&.GameOverWindow\&.IsWin\fR [get]\fP, \fR [set]\fP"

.PP
Получает или устанавливает флаг победы текущего игрока\&. 
.PP
Definition at line \fB30\fP of file \fBGameOverWindow\&.axaml\&.cs\fP\&.
.SS "\fBGameOverResult\fP? BattleShipGame\&.Views\&.GameOverWindow\&.Result\fR [get]\fP"

.PP
Получает выбранный пользователем результат\&. 
.PP
Definition at line \fB25\fP of file \fBGameOverWindow\&.axaml\&.cs\fP\&.
.SS "string BattleShipGame\&.Views\&.GameOverWindow\&.WinnerName = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Получает или устанавливает имя победителя\&. 
.PP
Definition at line \fB35\fP of file \fBGameOverWindow\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
