.TH "BattleShipGame.Models2.Ship" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Models2.Ship \- Представляет корабль в игре Морской Бой\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShip\fP (int size, bool horizontal)"
.br
.RI "Создает новый корабль\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSize\fP\fR [get, set]\fP"
.br
.RI "Размер корабля (количество палуб)\&. "
.ti -1c
.RI "List<(int X, int Y)> \fBPositions\fP\fR [get, set]\fP"
.br
.RI "Список позиций корабля на поле\&. "
.ti -1c
.RI "int \fBHitCount\fP\fR [get, set]\fP"
.br
.RI "Количество попаданий по кораблю\&. "
.ti -1c
.RI "bool \fBIsHorizontal\fP\fR [get, set]\fP"
.br
.RI "Ориентация корабля (true - горизонтальный, false - вертикальный)\&. "
.ti -1c
.RI "bool \fBIsSunk\fP\fR [get]\fP"
.br
.RI "Флаг, указывающий потоплен ли корабль\&. "
.in -1c
.SH "Detailed Description"
.PP 
Представляет корабль в игре Морской Бой\&. 
.PP
Definition at line \fB8\fP of file \fBShip\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Models2\&.Ship\&.Ship (int size, bool horizontal)"

.PP
Создает новый корабль\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP Размер корабля\&.
.br
\fIhorizontal\fP Ориентация корабля\&.
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBShip\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int BattleShipGame\&.Models2\&.Ship\&.HitCount\fR [get]\fP, \fR [set]\fP"

.PP
Количество попаданий по кораблю\&. 
.PP
Definition at line \fB22\fP of file \fBShip\&.cs\fP\&.
.SS "bool BattleShipGame\&.Models2\&.Ship\&.IsHorizontal\fR [get]\fP, \fR [set]\fP"

.PP
Ориентация корабля (true - горизонтальный, false - вертикальный)\&. 
.PP
Definition at line \fB26\fP of file \fBShip\&.cs\fP\&.
.SS "bool BattleShipGame\&.Models2\&.Ship\&.IsSunk\fR [get]\fP"

.PP
Флаг, указывающий потоплен ли корабль\&. 
.PP
Definition at line \fB30\fP of file \fBShip\&.cs\fP\&.
.SS "List<(int X, int Y)> BattleShipGame\&.Models2\&.Ship\&.Positions\fR [get]\fP, \fR [set]\fP"

.PP
Список позиций корабля на поле\&. 
.PP
Definition at line \fB18\fP of file \fBShip\&.cs\fP\&.
.SS "int BattleShipGame\&.Models2\&.Ship\&.Size\fR [get]\fP, \fR [set]\fP"

.PP
Размер корабля (количество палуб)\&. 
.PP
Definition at line \fB14\fP of file \fBShip\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
