.TH "BattleShipGame.Views.MainWindow" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Views.MainWindow \- Главное окно игры «Морской бой»\&. Поддерживает три режима: • против компьютера (с тремя уровнями сложности), • локальная игра на двоих, • сетевая игра через собственный сервер\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP ()"
.br
.RI "Инициализирует главное окно игры\&. Задаёт заголовок, размеры, фон и запускает экран загрузки\&. "
.in -1c
.SH "Detailed Description"
.PP 
Главное окно игры «Морской бой»\&. Поддерживает три режима: • против компьютера (с тремя уровнями сложности), • локальная игра на двоих, • сетевая игра через собственный сервер\&. 
.PP
Definition at line \fB24\fP of file \fBMainWindow\&.axaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Views\&.MainWindow\&.MainWindow ()"

.PP
Инициализирует главное окно игры\&. Задаёт заголовок, размеры, фон и запускает экран загрузки\&. 
.PP
Definition at line \fB197\fP of file \fBMainWindow\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
