.TH "BattleShipGame.App" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.App \- Основной класс приложения Avalonia\&. Отвечает за инициализацию приложения, создание главного окна и управление жизненным циклом\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.RI "Инициализация игрового сервера\&. "
.ti -1c
.RI "override async void \fBOnFrameworkInitializationCompleted\fP ()"
.br
.RI "Вызывается после завершения инициализации фреймворка Avalonia\&. Создает и запускает игровой сервер, настраивает главное окно\&. "
.in -1c
.SH "Detailed Description"
.PP 
Основной класс приложения Avalonia\&. Отвечает за инициализацию приложения, создание главного окна и управление жизненным циклом\&. 
.PP
Definition at line \fB21\fP of file \fBApp\&.axaml\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void BattleShipGame\&.App\&.Initialize ()"

.PP
Инициализация игрового сервера\&. Инициализирует приложение, загружая XAML-ресурсы\&. 
.PP
Definition at line \fB28\fP of file \fBApp\&.axaml\&.cs\fP\&.
.SS "override async void BattleShipGame\&.App\&.OnFrameworkInitializationCompleted ()"

.PP
Вызывается после завершения инициализации фреймворка Avalonia\&. Создает и запускает игровой сервер, настраивает главное окно\&. 
.PP
Definition at line \fB37\fP of file \fBApp\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
