.TH "BattleShipGame.ViewModels" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.ViewModels
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindowViewModel\fP"
.br
.RI "ViewModel для главного окна игры "Морской бой"\&. Управляет состоянием UI, видимостью экранов и игровой логикой\&. "
.ti -1c
.RI "class \fBViewModelBase\fP"
.br
.RI "Базовый класс для всех ViewModel в приложении\&. Наследует от ObservableObject из CommunityToolkit\&.Mvvm для реализации INotifyPropertyChanged\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
