.TH "BattleShipGame.ServerLogic" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.ServerLogic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClientMessage\fP"
.br
.RI "Представляет сообщение, полученное от клиента\&. "
.ti -1c
.RI "class \fBGameRoom\fP"
.br
.RI "Представляет игровую комнату для двух игроков\&. "
.ti -1c
.RI "class \fBNetworkMessage\fP"
.br
.ti -1c
.RI "class \fBNetworkClient\fP"
.br
.ti -1c
.RI "class \fBPlayerConnection\fP"
.br
.RI "Представляет подключение игрока к серверу\&. "
.ti -1c
.RI "class \fBServerMessage\fP"
.br
.RI "Представляет сообщение, отправляемое клиенту\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
