.TH "BattleShipGame.Views.DifficultyWindow" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Views.DifficultyWindow \- Окно выбора уровня сложности бота для режима игры против компьютера\&. Предоставляет выбор между тремя уровнями сложности: Легкий, Средний, Сложный\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDifficultyWindow\fP ()"
.br
.RI "Инициализирует новый экземпляр класса \fBDifficultyWindow\fP\&. Настраивает обработчики событий для кнопок выбора сложности\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBotDifficulty\fP? \fBSelectedDifficulty\fP\fR [get]\fP"
.br
.RI "Получает выбранный уровень сложности бота\&. "
.in -1c
.SH "Detailed Description"
.PP 
Окно выбора уровня сложности бота для режима игры против компьютера\&. Предоставляет выбор между тремя уровнями сложности: Легкий, Средний, Сложный\&. 

Используется только в режиме игры против компьютера (GameMode\&.VsComputer)\&. 
.PP
Definition at line \fB13\fP of file \fBDifficultyWindow\&.axaml\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BattleShipGame\&.Views\&.DifficultyWindow\&.DifficultyWindow ()"

.PP
Инициализирует новый экземпляр класса \fBDifficultyWindow\fP\&. Настраивает обработчики событий для кнопок выбора сложности\&. 
.PP
Definition at line \fB25\fP of file \fBDifficultyWindow\&.axaml\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBBotDifficulty\fP? BattleShipGame\&.Views\&.DifficultyWindow\&.SelectedDifficulty\fR [get]\fP"

.PP
Получает выбранный уровень сложности бота\&. Выбранный уровень сложности или null, если выбор не был сделан\&.
.PP
Definition at line \fB19\fP of file \fBDifficultyWindow\&.axaml\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
