.TH "BattleShipGame.ViewModels.ViewModelBase" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.ViewModels.ViewModelBase \- Базовый класс для всех ViewModel в приложении\&. Наследует от ObservableObject из CommunityToolkit\&.Mvvm для реализации INotifyPropertyChanged\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ObservableObject\&.
.PP
Inherited by \fBBattleShipGame\&.ViewModels\&.MainWindowViewModel\fP\&.
.SH "Detailed Description"
.PP 
Базовый класс для всех ViewModel в приложении\&. Наследует от ObservableObject из CommunityToolkit\&.Mvvm для реализации INotifyPropertyChanged\&. 

Все ViewModel должны наследоваться от этого класса для поддержки привязки данных\&. Предоставляет механизм уведомлений об изменении свойств\&. 
.PP
Definition at line \fB13\fP of file \fBViewModelBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
