.TH "BattleShipGame.Logic" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleShipGame.Logic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBotLogic\fP"
.br
.RI "Представляет основную логику бота\&. "
.ti -1c
.RI "class \fBBotTurnResult\fP"
.br
.RI "Результат хода бота\&. "
.ti -1c
.RI "class \fBBotManager\fP"
.br
.RI "Представляет класс для управления ботами\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
