.TH "Models2/BotDifficulty.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models2/BotDifficulty.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Models2\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBattleShipGame\&.Models2\&.BotDifficulty\fP { \fBBattleShipGame\&.Models2\&.Easy\fP, \fBBattleShipGame\&.Models2\&.Medium\fP, \fBBattleShipGame\&.Models2\&.Hard\fP }"
.br
.RI "Уровни сложности компьютерного противника\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
