.TH "Logic/BotLogic.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logic/BotLogic.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Logic\&.BotLogic\fP"
.br
.RI "Представляет основную логику бота\&. "
.ti -1c
.RI "class \fBBattleShipGame\&.Logic\&.BotTurnResult\fP"
.br
.RI "Результат хода бота\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Logic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
