.TH "Models2/CellState.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models2/CellState.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Models2\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBattleShipGame\&.Models2\&.CellState\fP { \fBBattleShipGame\&.Models2\&.Empty\fP, \fBBattleShipGame\&.Models2\&.Ship\fP, \fBBattleShipGame\&.Models2\&.Miss\fP, \fBBattleShipGame\&.Models2\&.Hit\fP, \fBBattleShipGame\&.Models2\&.Sunk\fP, \fBBattleShipGame\&.Models2\&.Blocked\fP }"
.br
.RI "Состояния клетки игрового поля\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
