.TH "Networking/ChatManager.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Networking/ChatManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Networking\&.ChatManager\fP"
.br
.RI "Класс \fR\fBChatManager\fP\fP управляет обменом текстовыми сообщениями между игроками в сетевой игре\&. Он интегрируется с сетевым клиентом и UI-компонентом чата (\fR\fBChatControl\fP\fP)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Networking\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
