.TH "ServerLogic/ClientMessage.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerLogic/ClientMessage.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.ServerLogic\&.ClientMessage\fP"
.br
.RI "Представляет сообщение, полученное от клиента\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.ServerLogic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
