.TH "Views Directory Reference" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChatControl\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBConfirmDialogWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBDifficultyWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameOverWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetworkConnectWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetworkGameOverWindow\&.axaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBOpponentDisconnectWindow\&.axaml\&.cs\fP"
.br
.in -1c
