.TH "Models2/GameMode.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models2/GameMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Models2\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBattleShipGame\&.Models2\&.GameMode\fP { \fBBattleShipGame\&.Models2\&.Menu\fP, \fBBattleShipGame\&.Models2\&.PlacingShips\fP, \fBBattleShipGame\&.Models2\&.VsComputer\fP, \fBBattleShipGame\&.Models2\&.VsPlayer\fP }"
.br
.RI "Режимы игры\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
