.TH "Models2/GameBoard.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models2/GameBoard.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Models2\&.GameBoard\fP"
.br
.RI "Игровое поле для Морского Боя\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Models2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
