.TH "Views/MainWindow.axaml.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/MainWindow.axaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Views\&.MainWindow\fP"
.br
.RI "Главное окно игры «Морской бой»\&. Поддерживает три режима: • против компьютера (с тремя уровнями сложности), • локальная игра на двоих, • сетевая игра через собственный сервер\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
