.TH "ViewModels/MainWindowViewModel.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModels/MainWindowViewModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.ViewModels\&.MainWindowViewModel\fP"
.br
.RI "ViewModel для главного окна игры "Морской бой"\&. Управляет состоянием UI, видимостью экранов и игровой логикой\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.ViewModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
