.TH "Views/NetworkGameOverWindow.axaml.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/NetworkGameOverWindow.axaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Views\&.NetworkGameOverWindow\fP"
.br
.RI "Диалоговое окно, отображаемое при завершении сетевой игры\&. Показывает результат игры и предоставляет опции для дальнейших действий\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Views\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBattleShipGame\&.Views\&.NetworkGameOverResult\fP { \fBBattleShipGame\&.Views\&.NewOnlineGame\fP, \fBBattleShipGame\&.Views\&.MainMenu\fP }"
.br
.RI "Перечисление возможных результатов после завершения сетевой игры\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
