.TH "Views/NetworkConnectWindow.axaml.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Views/NetworkConnectWindow.axaml.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Views\&.NetworkConnectWindow\fP"
.br
.RI "Окно подключения к сетевой игре\&. Позволяет пользователю ввести имя, адрес сервера и порт для подключения\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Views\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
