.TH "Networking/NetworkGameMode.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Networking/NetworkGameMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Networking\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBattleShipGame\&.Networking\&.NetworkGameMode\fP { \fBBattleShipGame\&.Networking\&.None\fP, \fBBattleShipGame\&.Networking\&.Searching\fP, \fBBattleShipGame\&.Networking\&.InGame\fP }"
.br
.RI "Режимы сетевой игры\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
