.TH "Networking/NetworkProtocol.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Networking/NetworkProtocol.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Networking\&.NetworkProtocol\fP"
.br
.RI "Статический класс, определяющий протокол обмена сообщениями между клиентом и сервером\&. "
.ti -1c
.RI "class \fBBattleShipGame\&.Networking\&.NetworkProtocol\&.Commands\fP"
.br
.RI "Типы сообщений (команды) используемые в протоколе\&. "
.ti -1c
.RI "class \fBBattleShipGame\&.Networking\&.NetworkProtocol\&.Keys\fP"
.br
.RI "Ключи данных, используемые в сообщениях протокола\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Networking\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
