.TH "Program.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Program\fP"
.br
.RI "Точка входа в приложение\&. Содержит методы инициализации и запуска Avalonia приложения\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
