.TH "Models2/SoundManager.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Models2/SoundManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.Models2\&.SoundManager\fP"
.br
.RI "Класс \fRSoundManager\fP предоставляет методы для воспроизведения звуковых эффектов в игре "Морской бой"\&. Звуки генерируются программно как синусоидальные тона и воспроизводятся через библиотеку NAudio\&. Все методы являются статическими и потокобезопасными благодаря асинхронному воспроизведению в отдельных задачах\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.Models2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
