.TH "ViewModels/ViewModelBase.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewModels/ViewModelBase.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.ViewModels\&.ViewModelBase\fP"
.br
.RI "Базовый класс для всех ViewModel в приложении\&. Наследует от ObservableObject из CommunityToolkit\&.Mvvm для реализации INotifyPropertyChanged\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.ti -1c
.RI "namespace \fBBattleShipGame\&.ViewModels\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
