.TH "ViewLocator.cs" 3 "BattleShipGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewLocator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBattleShipGame\&.ViewLocator\fP"
.br
.RI "Локатор представлений (View Locator) для паттерна MVVM\&. Преобразует ViewModel в соответствующий View на основе соглашения об именовании\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBattleShipGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BattleShipGame from the source code\&.
